# -*- coding: utf-8 -*-
"""Analyzing Sales data of ElectroGadget Pvt. Ltd 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RgP8JfhBCH0yFCljJO3khW-y6kK6rdvk
"""

import pandas as pd

pd.read_excel('/content/ElectroGadget.xlsx')

df=pd.read_excel('/content/ElectroGadget.xlsx')

df

df.info()

# we want to understand product performance, regional sales pattern and identify  high -value transactions

df.query('Product == "Tablet"').describe()  #product tablet performance

df.describe()

# Replace 'Region' with the actual column name for region in your DataFrame
# Replace 'North' with the name of a specific region
df.query('Region == "North"').describe()

df.query('Product == "Tablet" and Region == "North"').describe()

"""type casting

df[' SaleDate ']= pd.to_datetime(df[' SaleDate '], dayfirat=true)
"""

#summary statistics for key numerical columns
df.describe()

df.query("Product == 'Laptop' and `Units Sold`>1")

df.query("Product == 'Laptop' and `Units Sold`>1").describe()

# Sales in North region with revenue> 1000
df.query("Region == 'North' and `Revenue`>1000")

# USing OR with three conditions Questions. Sow transactions where:
'''Product is Laptop
OR Units Sold >5
OR Region is East'''

df.query("Product == 'Laptop' or `Units Sold`>5 or Region == 'East'")

df['Region']== 'East'

df[df['Region']=='East']

df[(df['Region']=='East' ) & (df['Product']=='Smartphone')]

df.loc[(df['Region']=='East' ) & (df['Product']=='Smartphone'), 'Units Sold':'Revenue']

df.loc[(df['Region']=='East' ) & (df['Product']=='Smartphone'),[ 'Units Sold','Revenue']]