# -*- coding: utf-8 -*-
""" Analyzing Sales data of ElectroGadget Pvt. Ltd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RgP8JfhBCH0yFCljJO3khW-y6kK6rdvk
"""

import pandas as pd

pd.read_excel('/content/ElectroGadget.xlsx')

df=pd.read_excel('/content/ElectroGadget.xlsx')

df

# product performance, regional sales pattern,  and identify  high-value transactions

df.query('Product == "Tablet"').describe()  #product tablet performance (statastical summary)

df.describe()

# Replace 'Region' with the actual column name for region in your DataFrame
# Replace 'North' with the name of a specific region
df.query('Region == "North"').describe()

df.query('Product == "Tablet" and Region == "North"').describe()
